# Generated by Django 2.1.5 on 2019-02-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190209_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publicationDate',
            field=models.DateField(null=True),
        ),
    ]
