# Generated by Django 2.1.5 on 2019-03-26 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190325_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishing',
            name='book',
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Publishing'),
            preserve_default=False,
        ),
    ]
