# Generated by Django 2.1.5 on 2019-02-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20190212_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.TextField(null=True),
        ),
    ]
