# Generated by Django 2.1.5 on 2019-04-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190403_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
