# Generated by Django 2.1.5 on 2019-04-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190406_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='/images/DefaultProfile.png', upload_to=''),
        ),
    ]
