# Generated by Django 2.1.5 on 2019-04-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190406_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginformation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
