# Generated by Django 2.1.5 on 2019-04-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190407_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginformation',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
