# Generated by Django 2.1.5 on 2019-04-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190407_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='/images/Default_Profile.png', upload_to=''),
        ),
    ]
