# Generated by Django 2.1.5 on 2019-03-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('biography', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('genre', models.CharField(max_length=120, null=True)),
                ('description', models.TextField(null=True)),
                ('publisher', models.CharField(max_length=120, null=True)),
                ('publicationDate', models.DateField(null=True)),
                ('ISBNThirteen', models.CharField(max_length=14, null=True)),
                ('ISBNTen', models.CharField(max_length=11, null=True)),
                ('pages', models.IntegerField(null=True)),
                ('authors', models.ManyToManyField(blank=True, to='books.Author')),
            ],
        ),
    ]
