# Generated by Django 2.1.5 on 2019-04-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
    ]
