# Generated by Django 2.1.5 on 2019-04-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('biography', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='bookID',
        ),
        migrations.RemoveField(
            model_name='book',
            name='content',
        ),
        migrations.AddField(
            model_name='book',
            name='ISBNTen',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ISBNThirteen',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publicationDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='books.Author'),
        ),
    ]
