# Generated by Django 2.1.5 on 2019-02-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_author_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ISBNTen',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ISBNThirteen',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(null=True),
        ),
    ]
