# Generated by Django 2.1.5 on 2019-02-16 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover'),
        ('cart', '0002_auto_20190216_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemsInCart', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.Book')),
            ],
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='itemsInCart',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='cartID',
            field=models.IntegerField(default=0),
        ),
    ]
