# Generated by Django 2.1.5 on 2019-02-16 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20190216_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='cartID',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.ShoppingCart'),
        ),
    ]
