# Generated by Django 2.1.5 on 2019-02-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
