# Generated by Django 2.1.5 on 2019-03-21 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_price'),
        ('cart', '0009_shoppingcart_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='cart.ShoppingCart')),
                ('itemsSaved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='books.Book')),
            ],
        ),
    ]
