# Generated by Django 2.1.5 on 2019-02-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=24),
        ),
    ]
